### ISSUE TITLE
Add link to Compiler's GitHub

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#11]
Make it the 3rd line:

```
hello@compiler.la

we build software for the government

github.com/compilerla
```

**Comment by AnthonyRollins** [comment]
I would actually recommend we use the Github logo and add it under the slogan `we build software for the government`
![GitHub-Mark-Light-64px](https://user-images.githubusercontent.com/25047205/174918845-356a29c6-44a5-466b-bede-8823b7681db7.png)

We can use the attached logo and link the image to [github.com/compilerla](https://github.com/compilerla).

**Comment by AnthonyRollins** [comment]
That makes a lot of sense to me. I was just thinking having two long-form links near each other wouldn't be visually appealing, but I could be wrong. We can talk more Friday to see what we can work out.

**Comment by AnthonyRollins** [comment]
![GitHub-Mark-Light-32px](https://user-images.githubusercontent.com/25047205/175610505-bf47f92a-680f-46c8-ac0a-5bb4d69dfa6a.png)
![GitHub-Mark-Light-64px](https://user-images.githubusercontent.com/25047205/175610508-414119f3-9ed4-40f4-a76a-711ddd6efe21.png)
![GitHub-Mark-Light-120px-plus](https://user-images.githubusercontent.com/25047205/175610509-93784c0e-e332-4ef0-ac37-78c6c8ba3daa.png)
