### ISSUE TITLE
Development work for Nav

### ISSUE THREAD

**Issue by machikoyasuda** [compilerla/compiler.la#110]
We skipped the Nav for the Jobs/Career Milestone, so we are adding it here for the Home Page milestone.

### Menu trigger icon button:

- For focus, let's give this the same treatment as the buttons: 1.5px green border with 4px padding between border and hamburger icon
- For hover, let's have it go to brand/primary/gray. Not really noticeable but I don't think this really needs a hover state? - lmk if you think otherwise!

### Menu close icon button:

- Same as trigger buton

### Menu link:

- Underline on hover, remain white.
- Standard H2 (40/32)

**Comment by segacy1** [comment]
Hey @machikoyasuda @angela-tran I may need to play around with the graphic on the open menu page a bit to get it right. Could we please use this graphic to start and you could show me how it looks? 
![262683671-d77c0aff-91c4-4524-aec8-955563a27ee7](https://github.com/compilerla/compiler.la/assets/33331853/925c76d1-980b-43ac-8b52-ee97f2835a96)
