### ISSUE TITLE
Footer social media icon bug

### ISSUE THREAD

**Issue by machikoyasuda** [compilerla/compiler.la#115]
- Needs to be a brighter/lighter color
- Convert to SVG

**Comment by machikoyasuda** [comment]
@segacy1 What should the color be on load and on hover?

**Comment by segacy1** [comment]
[social icons.zip](https://github.com/compilerla/compiler.la/files/12455412/social.icons.zip)
@machikoyasuda let's have this mirror the hamburger menu active and hover states
