### ISSUE TITLE
Design for 404 Page

### ISSUE THREAD

**Issue by segacy1** [compilerla/compiler.la#120]
Design a branded design to replace Netflify's default 404:
<img width="1328" alt="Screenshot 2023-08-28 at 11 31 15 AM" src="https://github.com/compilerla/compiler.la/assets/33331853/6777becb-abf3-41fc-a407-ae898970cef4">

**Comment by segacy1** [comment]
cc @machikoyasuda @thekaveman @AnthonyRollins

**Comment by segacy1** [comment]
Two very basic ideas for our 404 page [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=1997-923&mode=design). Thoughts? And do we want to update this copy?

**Comment by AnthonyRollins** [comment]
@segacy1 I like option 2 as I like the idea of keeping the 404 page pretty simple. As for copy - what you have there works for me: `Something’s missing! The page you're looking for doesn’t exist or was removed. We suggest you go back home`

**Comment by thekaveman** [comment]
I also like the simpler option 2, but I wonder if we can make the alert icon a different one of our colors, just for some more splash?

**Comment by segacy1** [comment]
@thekaveman @AnthonyRollins added a version with a cyan icon for you to check out + updated to "something's missing!" copy

**Comment by AnthonyRollins** [comment]
@segacy1 I don't think we need to go through the extra work, but it would be cool if the `Exclamation mark` cycled through all of our cyan, green, and purple colors.
