### ISSUE TITLE
Design blog list and post page

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#122]
After some discussion on the feasibility of launching a blog on our website (see #114), we decided it makes the most sense to build a blog on our website rather than using a third-party platform like [Ghost](https://ghost.org/).

**Design**
We want the blog's functionality modeled after the calitp.org Press list page and press post page but with the Compiler's branding. 

_Blog List Page_
We are still working on the assets we want to include, but @laneymangan and @AnthonyRollins can follow up after discussing them with the blog committee team. We would like to have a title, date and author name. We will confirm if there are other things we would like to include, like a category option for (Wrap-ups and Quarterly Posts) 

_Blog Posts Page_
The blog posts page should also include a title, subtitle, date and author name, and the ability to add images in-line with text. We don't need imagery in the header background section, but having the Compiler's brandmark or something might be nice to make the title more visually appealing.

**Comment by AnthonyRollins** [comment]
@segacy1 I moved this status to `Work on Next` as we prioritize getting this out by the end of the month. We will push back the `Work page` until later this month or early next month. Let me know if we can start work on the designs for a blog for the next few weeks.

**Comment by segacy1** [comment]
For sure!

**Comment by machikoyasuda** [comment]
@segacy1 Just a suggestion - for the post page typography, it might be nice to design type for pulled quotes and featured image with a caption.

**Comment by segacy1** [comment]
Hey folks! I wanted to share some [initial designs](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=2120-5427&mode=design) for a first round of feedback.
@AnthonyRollins @o-ram @thekaveman @machikoyasuda @angela-tran 

**Blog Listing Page**

I’ve designed three versions, each with a bit more content shown than the last, with options for tagging and filtering by category. If we want a filter, I’d recommend the dropdown field over the filter pills we use on calitp.org because 1) it’s a lot easier to scale and 2) we already have a similar pill design for the page labels. 

**Blog Post Page**

I’ve designed two versions of this page. One thing to note is that I included an option for a white background. Since this will be a lot of text for folks to read, I think the consensus is black text on a white background is easier to read than white text on a black background. I can pull some sources on that if we’re interested/want some confirmation. Also:

- I created two additional blocks for Further Reading and Newsletter at the bottom of these pages. We can have one or both.
- I haven’t included categories on these designs, but they’d be easy to add. 

Note: These designs aren’t final or pixel-perfect but I wanted to give an opportunity for feedback before I continued to iterate. If there’s a blog out there you like, feel free to share it with me for inspo.

@AnthonyRollins I'm still thinking through the brandmark or graphic on the blog post pages

**Comment by segacy1** [comment]
Some feedback from @indexing: 

1. Will we have Headings and Subheading styles? I think the ability to break longer posts into sections will be important.
2. Aside from the browser back button, will there be in-app navigation to return to list of blog posts?

**Comment by laneymangan** [comment]
Excited to take a look! Flagging this to @MerylGreen as well. @segacy1 do we have a compiler company account for Figma or should I create my own account and request access?

**Comment by segacy1** [comment]
@laneymangan hi! I think you'd need to create your own account with compiler and request access. Let me know if you have trouble

**Comment by AnthonyRollins** [comment]
@ segacy1 I am responding to your questions and thoughts, below.

**Blog Listing Design**
> I’d recommend a dropdown field over the filter pills we use on calitp.org because 1) it’s a lot easier to scale and 2) we already have a similar pill design for the page labels.

The dropdown field works for me, but I am curious from dev if that is easy to implement, as the blog team is still figuring out the filters.

As for the designs, I like the 3rd option w/ Categories - I added a thumbs-up comment to the one I prefer

**Blog Page Designs**

> I think the consensus is black text on a white background is easier to read than white text on a black background.

I like the white background

> I created two additional blocks for Further Reading and Newsletter at the bottom of these pages. We can have one or both.

We don't have a Compiler Newsletter, only a newsletter for future job postings, so the Further Reading section makes more sense.

As for designs, I thumbed up the one I prefer: the no photo, white background with all text aligned in the center.

> I'm still thinking through the brandmark or graphic on the blog post pages

The brandmark isn't necessary to include, but it might be something we could use to add some color.

>  Will we have Headings and Subheading styles? I think the ability to break longer posts into sections will be important.
Aside from the browser back button, will there be in-app navigation to return to list of blog posts?

I agree with Andy to include some headings and subheadings to break up the content if needed. I do like the idea to have a return to the blog list page, as an option. 

Very long post, but I hope this is helpful.

**Comment by thekaveman** [comment]
I haven't looked at the proposals yet, but I just want everyone to keep in mind:

Features like filters and sorting etc. for a listing page require lots of content to be meaningful. My take is we iterate on a list page that starts very simply for the handful of posts we might have over the next few months. As our content calendar is tightened up we can look to add more features to the listing page that make sense when there is a larger list to work with.

**Comment by segacy1** [comment]
Do we know yet what we want our publishing cadence to look like (e.g. one post per month?) and if we'll launch with just one post or a handful? 

And @thekaveman agreed - we can save those more complex additions for later when we have more content

**Comment by AnthonyRollins** [comment]
> Features like filters and sorting etc. for a listing page require lots of content to be meaningful. My take is we iterate on a list page that starts very simply for the handful of posts we might have over the next few months. As our content calendar is tightened up we can look to add more features to the listing page that make sense when there is a larger list to work with.

@thekaveman That makes a lot of sense to me, as filtering won't matter until we have multiple posts. 

> Do we know yet what we want our publishing cadence to look like (e.g. one post per month?) and if we'll launch with just one post or a handful?

@segacy1 Our cadence is a quarterly(long-form content) post and monthly smaller posts. We are looking to have our first short-form post when we launch and then follow shortly behind with a long-form post. You can see the list of the topic ideas in our [Blog ClickUp List](https://app.clickup.com/8631512/v/li/900900065519) and the one-pager on the [ClickUp Blog](https://app.clickup.com/8631512/v/dc/87d6r-7568/87d6r-17347)

**Comment by laneymangan** [comment]
I think they look great, @segacy1! thank you! I agree with all of the above discussion. I commented on my preferred options

**Comment by segacy1** [comment]
I've updated the listing and post pages with the most votes so far [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=2276-969&mode=design&t=BCYLmnMghg0xxpnL-4) (under "Design Round Two"). Updates are: 

**Listing Page**
- remove filter on listing page

**Post page**
- add "back" button in a subnav
- add styling for headers and subheaders 
- keep "further reading" section

What do folks think about moving forward with these? Is there any other feedback you'd like to see implemented?
cc @AnthonyRollins @laneymangan

**Comment by AnthonyRollins** [comment]
@segacy1 I am good to move forward with these designs, but I did have two notes about the designs. 

> add "back" button in a subnav

We should also have a back button at the end of the blog post content. 

> add styling for headers and subheaders

I don't think we need a subheader for blog headings, but curious what you think @laneymangan.

> I've also added an idea underneath for tagging with categories, but still not including filters.

I think we can look into this for our blog v2, and keep it simple for now.

**Comment by thekaveman** [comment]
>> add styling for headers and subheaders

> I don't think we need a subheader for blog headings, but curious what you think @laneymangan.

@AnthonyRollins I think this is about in-content, to be able to have e.g. `h2`, `h3`, `h4` levels of various sections and sub-sections within a post. I think we should at least have and `h2` style, but probably `h3` as well.

**Comment by segacy1** [comment]
In that case, design is just about ready. Two questions from me before wrapping up:

1. Do we want to stick with the image I pulled for the blog listing page hero? @AnthonyRollins 
2. The blog post page design calls for a new header style (Source Code Pro, 24px) and I'm not sure how best to name it. I could slap it on the end of our header list as h6 since already have h1-5, but I don't know if that's confusing with headers otherwise descending in size (h1 Is 48px, h5 is 16px). I could give it a blog-specific name, but I'd like the option to use it elsewhere on the site. @thekaveman @machikoyasuda @angela-tran do you have any preference?

**Comment by machikoyasuda** [comment]
If you want the option to use it elsewhere on the site, I think it should be an h4. And change the current h4 to h5. Then change the current h5 to h6. As far as I can tell, h5 (font size 16px) is not used anywhere in the app yet. 

<img width="732" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/955056fa-b0c8-428b-84e1-80d4b74ea8b9">

**Comment by segacy1** [comment]
works for me, thanks @machikoyasuda!

**Comment by AnthonyRollins** [comment]
@ segacy1 The photo looks good to me. We have more recent photos with more of the [team here](https://drive.google.com/open?id=1GnZZBkr7MRL525ByMgdfWlnmXrnAlrCg&usp=drive_fs), so if you find something you like more, you can use it.

**Comment by machikoyasuda** [comment]
From today til next Friday (9/29) is our engineering slush week (the downtime week before sprints, so we can work on non-Cal-ITP projects), so I'm available to work on biulding the blog and blog post pages out. Is this design ready? @AnthonyRollins @segacy1

**Comment by segacy1** [comment]
@machikoyasuda just about, I'll tag you when it's done!

**Comment by segacy1** [comment]
@AnthonyRollins I realize we probably would need a line of copy for this section. Would you like us to go with _Our Blog_? Would you like to add an intro? 
<img width="1003" alt="Screenshot 2023-09-21 at 11 52 32 AM" src="https://github.com/compilerla/compiler.la/assets/33331853/b9b0cf73-3a8b-4f22-949b-2a584722036b">

**Comment by AnthonyRollins** [comment]
`Our Blog` as a title is fine; we have some thoughts on changing that in the future - see [#blog channel](https://compilerla.slack.com/archives/C05L2B0SG06). 

For copy we can go with: `An inside look at Compiler's internal projects, interests and our client projects.` Definitely open to changing that content, but I think that should work for now.

**Comment by segacy1** [comment]
Design is complete! Designs ready for dev can be found [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=2394-2322&mode=design)
