### ISSUE TITLE
Clean up file structure, devcontainer

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#123]
- [ ] Move all site content / assets into a `src/` directory
- [ ] Update the Jekyll config to build from this directory
- [ ] Update the devcontainer build to account for new directory if needed
- [ ] Update the devcontainer base image to python 3.11
- [ ] Make devcontainer use a non-root user
- [ ] `.prettierrc` to control indentation and other formatting

**Comment by machikoyasuda** [comment]
- [ ] use pyproject.toml (https://github.com/cal-itp/benefits/blob/dev/pyproject.toml)
