### ISSUE TITLE
Credit artist for the employee illustrations on About page

### ISSUE THREAD

**Issue by shelby-e** [compilerla/compiler.la#125]
Please credit @worksofharte (see her Instagram url below) for the illustrations on the About page. Perhaps something like "Illustrations by @worksofharte" underneath the illustrations?
https://www.instagram.com/worksofharte/

**Comment by segacy1** [comment]
@AnthonyRollins @shelby-e how's [this](https://www.figma.com/proto/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?page-id=2110%3A136&type=design&node-id=2110-1510&viewport=417%2C484%2C0.12&t=ywtVv74DjEXId9wB-1&scaling=min-zoom&mode=design)?
