### ISSUE TITLE
Development for blog listing, blog post page

### ISSUE THREAD

**Issue by machikoyasuda** [compilerla/compiler.la#129]
## Blog list page
- URL: `/blog/`
- Header section with copy (pill, h1, tagline) and image (alt tag)
- Show up to 4 of the latest posts in reverse chronological order
- Typography: Post title as a link, byline, dateline, excerpt
- Excerpt (teaser sentence): Custom sentence (provided by the writer)
- Back button section

## Blog post page
- URL: `/blog/YEAR/permalink-goes-here/`
- Header title section with copy. Optional subtitle.
- White post content section
- Byline: Author list (Can be 1 person or multiple - connected with the word "and")
- Typography: Subheaders (h2), tagline, blockquote, image (full-width, left-align) with caption and byline for the photographer
- Back button at top and bottom
- Read more from us section

## After it's all done
- Add first post, could be added as a draft until ready
- Add Blog link to the nav menu

**Comment by o-ram** [comment]
@AnthonyRollins These are my notes from the conversation, putting it in this ticket for visibility. It looks to all be included within Machiko's list above.

### Home page: 
Each blog on the page should include the following:

- Title
- Byline
- Date
- Teaser (custom)

### Post page
Each blog post page should include the following:

- Headline
- Byline
- Optional subtitle

Within the post, content can include:

- section titles
- pulled quote (150 characters or fewer)
- Illustrations (need to be accompanied by its own byline or caption)
