### ISSUE TITLE
Design illustration for blog post sharing

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#138]
Related to #129 

Design an illustration that can be used for blog post sharing on LinkedIn, Slack and other platforms. Look at the [slack thread](https://compilerla.slack.com/archives/C04BN95SH0S/p1695941883462499) for the complete discussion of this issue.

**Comment by segacy1** [comment]
@AnthonyRollins I kept it pretty simple! The three rows are essentially the three general ideas with some visual variation. Not sure if this is something that's a hassle to swap later down the road, so happy to iterate!

cc @machikoyasuda

**Comment by machikoyasuda** [comment]
@AnthonyRollins Do you have a choice amongst these?
<img width="858" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/07233099-e56d-4654-ba09-acabd77126e0">

**Comment by thekaveman** [comment]
My picks: `2b`, `2c`, `2e`

Except the wording on `2c` isn't anything I'm familiar with as a brand message?

**Comment by segacy1** [comment]
@thekaveman yep! it's not anything official, just a sample line I added based on our homepage copy. Can def change it to an official tagline

**Comment by AnthonyRollins** [comment]
@segacy1 Let's go with `2b`

**Comment by machikoyasuda** [comment]
@segacy1 

So for 2b, I will just need a PNG of the black rectangle - and then I can code it all up!

<img width="342" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/27a771f3-5063-4aa6-9e81-c188ccea67c7">
