### ISSUE TITLE
Client testimonial - SCAG

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#152]
As we wait for a client testimonial from Caltrans, we would like to start the progress on the possibility of getting a quote from someone at SCAG for Compiler's work. Ideally, we need another quote for the new Work page, so we should look into other potential clients for quotes.

[Current designs](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=1751-1516&mode=design&t=74UssuidcGfJrYHg-0) (see design option number 3 final designs) for the Work page
[Content doc ](https://docs.google.com/document/d/1MVg0KN4Lkq3AiiTmotIC0dH_m-fRwItsLfJiok2N-B4/edit)for Work page

**Comment by AnthonyRollins** [comment]
@thekaveman Could we get your help with figuring out the right person for this? We can help draft a quote that we can send for approval.

**Comment by o-ram** [comment]
Update: we can ask SCAG. Kegan has one or two people who were close enough to the project and might be willing to provide one. We will provide Kegan w/ the email and testimonial template, and he will forward it along to the SCAG contacts with us copied.

**Comment by o-ram** [comment]
Testimonial from SCAG has been approved for us to use and is included within the copy for the work page.
