### ISSUE TITLE
Build out current website design in Figma

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#16]
Using the styling from our current [website](https://compiler.la) and [Figma designs](https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website):

- [x] Build out the Compiler homepage in Figma
- [x] Add in button design and changes listed in #9 
- [x] Get owner access to past [Figma designs](https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website)

**Comment by AnthonyRollins** [comment]
Created a separate issue, so we can make comments separately from #9 related to the Figma designs.

**Comment by thekaveman** [comment]
@AnthonyRollins when you say copy that format - what do you mean? For the Figma file organization? Or do you mean the table layout I used above in my comment?

I think that's what you're suggesting we add to this repo's README? If so, good idea!

**Comment by angela-tran** [comment]
@srhhnry Perhaps you could help us with Figma permissions. See Kegan's message in https://compilerla.slack.com/archives/C02GQ7AJXQE/p1658174719018529

When I click any of the links in https://github.com/compilerla/compiler.la/issues/16#issuecomment-1187691752, I see one of these messages:
```
File not found

Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.
```

```
Prototype not found

Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.
```

**Comment by thekaveman** [comment]
@angela-tran I'm going to delete your user and re-add you in Figma. I'm seeing a strange difference between yours and Anthony's accounts, not sure how else to change it.

**Comment by thekaveman** [comment]
Did that for both @angela-tran and @machikoyasuda and now your accounts have the same "Team View" permission that Anthony's does. Try again?

**Comment by thekaveman** [comment]
@AnthonyRollins I'm closing this - we posted the links in the README and I confirmed I have edit access to the other Compiler website Figma file.
