### ISSUE TITLE
Add Marissa + illustration to "Meet the team" on About page

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#160]

**Comment by AnthonyRollins** [comment]
Here is Marissa's watercolor [image](https://drive.google.com/file/d/1uD9xT-Swz1UHh9zJ3wYo5Yn16Izlu4r1/view?usp=drive_link). Her title should be labeled as Product Manager.

**Comment by thekaveman** [comment]
@machikoyasuda did you add the white background and rounded corners to the team images?

The one that @AnthonyRollins linked above for Marissa is just a large transparent background.

**Comment by thekaveman** [comment]
@machikoyasuda ping :point_up: 

> did you add the white background and rounded corners to the team images?

**Comment by machikoyasuda** [comment]
@thekaveman No I didn't. I got the photos all prepped and ready from someone else. That's beyond my photoediting skills 😅

**Comment by machikoyasuda** [comment]
@thekaveman @AnthonyRollins 
Dimensions: 300 × 276
PNG

That image is going to have to be cropped to be more square-ish and put the person in the center (horizontally), and have the head start from 20ish pixels from the top and have the bottom go close to the bottom edge (to reduce the floating ghost vibe) - to get close to matching everyone else. 
![image](https://github.com/compilerla/compiler.la/assets/3673236/24d74869-1979-4ea8-b9a9-ddb48b311aa3)

**Comment by AnthonyRollins** [comment]
@thekaveman @machikoyasuda I believe Segacy updated these photos, so is it possible that @srhhnry (Welcome back!) or @indexing might be able to help here?

**Comment by srhhnry** [comment]
If someone can point me to the other files I can make this more exact, but here's an approximation:
![Marissa Photo](https://github.com/compilerla/compiler.la/assets/5394204/5ed182be-550a-4be7-a719-e74bc6382ae8)

**Comment by thekaveman** [comment]
Thank you @srhhnry! All the existing files for the site are here: https://github.com/compilerla/compiler.la/tree/main/assets/team_members

**Comment by srhhnry** [comment]
Looks like I don't have access to upload so dropping the updated file here: 
![Marissa-Rosemblat](https://github.com/compilerla/compiler.la/assets/5394204/10036daa-b7b1-4f1c-b8f7-71101c54cc17)

**Comment by thekaveman** [comment]
@machikoyasuda can you please finish this update as well?
