### ISSUE TITLE
Add new employee images to website

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#183]
Add four new employee watercolor images to the "Meet the team" section of the website.

Images will be found in [this folder](https://drive.google.com/drive/u/0/folders/1GfXK5v_csUZ0yksVNY4w3nnRLtjlhVUQ) once they have been created.

**Comment by AnthonyRollins** [comment]
All new employees' images have been uploaded. The new employees are: `luis-alvergue.png` `marie-araneta.png` `nina-dinh.png` `adam-linder.png`

@srhhnry I believe the image backgrounds need to be updated to match the other images on the website, see #160.

**Comment by AnthonyRollins** [comment]
Job titles for everyone:
- Luis: Senior Software Engineer
- Marie Araneta: Account Manager
- Nina Dinh: Account Manager
- Adam Linder: Account Manager
