### ISSUE TITLE
Workflow for resume collection

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#19]
On Compiler's [Jobs page](https://compiler.la/jobs), there is a place where users can send us their resumes when there are no open positions. We need to find an internal and external workflow for applicants who want to send us their resumes.

**Comment by AnthonyRollins** [comment]
From @vykster on Slack: 

two quick thoughts on this

1. send us your resume is a new workflow — is this something we are ready for? it hasn’t been discussed that I know of. What’s the benefit/experience like for the applicant and what’s the benfit/work look like for our team?
2. I did set up a new mailchimp listserv we can use to send notices of new job postings. we have just a few subscribers thanks to our current hiring effort for a senior designer.

**Comment by AnthonyRollins** [comment]
Thanks. To respond to your other messages. We added in that line of text and I didn't consider the needs for a workflow as I added it in there to see if people would actually use it. But I can definitely see the use cases in having a workflow, so people know we received their email and that we are correctly tagging it in our system so we can pull from later. I really like the idea of using Mailchimp.

**Comment by vykster** [comment]
I think what I was hinting at here -- was you're likely making more work for someone on the team! Not a bad thing persay but let's make sure we're ready for it?  I don't believe we have Shelby set up in our GitHub. @AnthonyRollins can you help bring Shelby into the conversation. 

I think maybe let's switch the text on the site to direct folks to the mailchimp signup until we're able to make a plan for collecting and reacting to people sending us resumes.

**Comment by AnthonyRollins** [comment]
@vykster Yeah, this all makes sense; I think Mailchimp is a great option. I will loop Shelby into this conversation and get her thoughts on this approach to the website. I would like to keep the conversation on Github so that everything website-related stays in the same place, but I will discuss it with Shelby. 

You have 2FA on Mailchimp, so I haven't been able to log in, let me know when you are available to send the code or for a short period you can turn it off and then turn it back on. After I get access I will grab the Mailchimp link from the site and add it to an issue for @angela-tran to add to the website.

**Comment by thekaveman** [comment]
> You have 2FA on Mailchimp

Just FYI @vykster @AnthonyRollins a new option I have been exploring to overcome this issue is using LastPass as the 2FA device! The profile page for the username/password then has a place where it generates the code:

Here's a screenshot from the @compiler-bot LastPass page:

![image](https://user-images.githubusercontent.com/1783439/179799785-e85fb714-6ee7-4a8c-b571-5d0cb660af98.png)

So when you share the account with someone in LastPass, they can also use the 2FA code!

**Comment by angela-tran** [comment]
Also an FYI on LastPass: if you edit an item you've already shared (so for example, you add 2FA to the item), you need to re-share it for recipients to get the update. This is according to LastPass's help center: https://support.lastpass.com/help/use-the-sharing-center-lp020007

@thekaveman Could you re-share the Compiler bot item with me? 2FA hasn't worked for me with it, and this would be a nice test!

**Comment by angela-tran** [comment]
It worked! Thanks @thekaveman

**Comment by AnthonyRollins** [comment]
I've always wondered what the one-time password was used for.

**Comment by vykster** [comment]
Here's the mailchimp link: http://eepurl.com/h6qTKL

I'll look into seeing if I can change the 2FA auth.

Vyki

**Comment by vykster** [comment]
ok sweet that was fun. moved it into a new shared data-donuts folder anyways.

**Comment by AnthonyRollins** [comment]
I was able to login to the platform 🥳

**Comment by o-ram** [comment]
Closing this issue as we have moved our MailChimp forms to Hubspot.
