### ISSUE TITLE
Replace team photo on blog page

### ISSUE THREAD

**Issue by shelby-e** [compilerla/compiler.la#253]
When possible, please replace the team photo on Compiler's blog page with the photo taken in October 2024. [This is the Slack thread that will direct you to the photo to use.](https://compilerla.slack.com/archives/C04BN95SH0S/p1730943161382019)
I am submitting a speaker application this week for a conference that is in August 2025. Application reviewers will likely review application in January and February 2025, so if it can be updated by then, that would be excellent. I'd love to more accurately reflect Compiler's team. Thank you!

**Comment by thekaveman** [comment]
Waiting for a bugfix in `rubygems` blocking the building of the site. 

https://compilerla.slack.com/archives/C02GQ7AJXQE/p1734453355735609
