### ISSUE TITLE
Fix devcontainer dependency issue

### ISSUE THREAD

**Issue by angela-tran** [compilerla/compiler.la#27]
This error shows when trying to open the devcontainer:
```
#0 29.70   Attempting uninstall: distlib
#0 29.71     Found existing installation: distlib 0.3.3
#0 29.71 ERROR: Cannot uninstall 'distlib'. It is a distutils installed project
and thus we cannot accurately determine which files belong to it which would lea
d to only a partial uninstall.
------
failed to solve: executor failed running [/bin/sh -c python3 -m pip install --up
[2022-08-10T17:31:59.138Z] 
grade pip &&     pip install pre-commit]: exit code: 1
```

Not sure what changed to cause this, but it seems like something external to our code. To fix this, we could try using a virtual environment within the Docker container or redoing the container setup to be based on a different image.

**Comment by thekaveman** [comment]
I noticed the same issue in MobiMart, [hence why I previously activated a `venv`](https://github.com/cal-itp/mobility-marketplace/pull/352/commits/d3def7c676ec42fc71d4eb69e0d2b07139ce271c#diff-13bd9d7a30bf46656bc81f1ad5b908a627f9247be3f7d76df862b0578b534fc6R6).

Moving to the `python:3.10` image and just installing ruby/Jekyll in there seemed... cleaner?
