### ISSUE TITLE
Add Amplitude to website 

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#28]
## To-Do

- [ ] Setup [amplitude](https://amplitude.com/) under the Compiler account
- [ ] Add tracking events for form submissions, page views, clicks, etc.

**Comment by machikoyasuda** [comment]
Just FYI, there is Google Analytics set up for the site already.

**Comment by AnthonyRollins** [comment]
@thekaveman @machikoyasuda Is there a benefit to having amplitude instead of Google Analytics on our website?

**Comment by thekaveman** [comment]
Probably not - Amplitude is more suited to tracking specific user flows and actions in something closer to an app; whereas Google Analytics is probably what we want for a mostly informational website.

We can still do GA events if we want to get more specific on e.g. clicks on a Job Apply link.

**Comment by AnthonyRollins** [comment]
Ok, so we can close out this issue as we decided to stick with GA for now.
