### ISSUE TITLE
Update fonts and colors

### ISSUE THREAD

**Issue by angela-tran** [compilerla/compiler.la#37]
Once the styling updates in #33 have been finalized in Figma, we can start incorporating those changes by updating the font sizes and colors.

**Comment by machikoyasuda** [comment]
<img width="822" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/4b1b94ae-60c3-4071-af98-bd91b7ee1dfe">
<img width="861" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/8b3a682b-019f-4fdb-abcb-e7d2c5c85da0">

**Comment by machikoyasuda** [comment]
Also, make small tweaks to Button to match designs
