### ISSUE TITLE
Consider max width for site

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#38]
Just a thought: I have a super widescreen, and the site currently expands to fill the entire viewport. Not necessarily a problem, but it might be more readable if we imposed a max width with the content center aligned and increased margins/padding on the sides.

Here's a screenshot of the homepage at full width on my screen:

<img width="1874" alt="image" src="https://user-images.githubusercontent.com/1783439/208964325-493bd703-6b14-40b3-af1f-d567c402f626.png">

And another of the current job posting:

<img width="1861" alt="image" src="https://user-images.githubusercontent.com/1783439/208964428-fa17f1b3-aa4f-41a5-a00d-c52cd16c71b6.png">

**Comment by machikoyasuda** [comment]
This is done with #106 as well
