### ISSUE TITLE
Document brand work for workshop

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#45]
After concluding our website workshop on Feb 14th 2023, we need to capture the findings from those meetings to provide an update to the rest of the team who couldn't attend the workshop. 

## To-Do
- [x] Document brand work from the workshop
- [x] Report out to the Compiler team in [#websites channel](https://compilerla.slack.com/archives/C04BN95SH0S)

**Comment by AnthonyRollins** [comment]
@ segacy1 When will you be able to send out this report from the website workshop? @o-ram and I were thinking of getting the roadmap out by mid to late next week, and we could do this together as one big update.

**Comment by segacy1** [comment]
Sounds good, @AnthonyRollins. I'll circle back tomorrow and let you know if I can wrap this up before my OOO starts on Monday!

**Comment by segacy1** [comment]
Here's a link to the page in [Figma](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?node-id=803%3A21993) or you can view it as a [prototype](https://www.figma.com/proto/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?page-id=803%3A21993&node-id=805%3A4230&viewport=1051%2C20%2C0.05&scaling=contain). I'll flesh this out a bit more when I get back, but I think it's okay for you to send along with your roadmap update if you'd like!

**Comment by AnthonyRollins** [comment]
We will get this added to our report; thank you!
