### ISSUE TITLE
Build out the first draft of the website roadmap in Clickup whiteboard

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#47]

**Comment by o-ram** [comment]
@AnthonyRollins [here](https://app.clickup.com/8631512/v/dc/87d6r-5900) is a first draft with those changes we talked about. I do have some questions I'm hoping we can discuss at our next meeting, mostly surrounding the Jobs page updates that are _not_ set for Q1.

**Comment by AnthonyRollins** [comment]
@o-ram I think we can close this issue, as we finished the first draft.
