### ISSUE TITLE
Text appears on top of button on job posting

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#52]
## Context
The bottom content appears over the Apply Now button on the latest job posting for the [Senior Consultant, Product Manager](https://compiler.la/jobs/product-manager). This position no longer accepts applications, so this isn't an urgent fix, but it should be resolved before our next post. No other job posting pages are affected as they don't have the Apply now button.

## Screenshots
Desktop
![Screenshot 2023-03-20 at 3 23 06 PM](https://user-images.githubusercontent.com/25047205/226478953-659d4bff-008d-469d-8596-bd6a47600cc2.png)

Mobile
![Screenshot 2023-03-20 at 3 22 36 PM](https://user-images.githubusercontent.com/25047205/226478992-c6b1febd-805d-4d95-80e9-88d30b760440.png)

**Comment by angela-tran** [comment]
Thank you @AnthonyRollins!
