### ISSUE TITLE
Refactor job `open` boolean to instead be an expiration date

### ISSUE THREAD

**Issue by angela-tran** [compilerla/compiler.la#54]
Currently our job page [looks for a variable named `open`](https://github.com/compilerla/compiler.la/blob/0ee42f8fd4078663cc94def80933d9468bc4c131/jobs.html#L8) for each job to decide whether it shows up in "Accepting applications" or "Past opportunities". This means that when a job is no longer open, we have to open a pull request to update the boolean. (See #42 and #48.)

We could instead have an expiration date variable on the job and have logic that checks the relationship between that date and the current date.

I'm not sure what the implementation would look like. This would have to be dynamic logic on the page rather than generated by Jekyll.

**Comment by thekaveman** [comment]
Which means it would have to be done in browser-local time vs. California/Compiler time.

I like the idea though. Maybe [`moment.js`](https://momentjs.com/) could help here?

**Comment by vykster** [comment]
we actually do this on the data and donuts site and it still takes a pr to rebuild the site. I imagine you have the deploy set up differently here?

**Comment by thekaveman** [comment]
I'm looking at both [Day.js](https://day.js.org/en/) and [Luxon](https://moment.github.io/luxon/#/) as alternatives to Moment.js for handling dates/CA-local time in JS, as it seems Moment.js advises against using it in new projects:

> We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.
> ...
> In most cases, you should not choose Moment for new projects.

From https://momentjs.com/docs/#/-project-status/recommendations/

Leaning towards Luxon as it seems to be able to handle timezones without additional plugins/libraries. Though I do like the easy syntax of Day.js's helper functions like [`isBefore`](https://day.js.org/docs/en/query/is-before) and [`isAfter`](https://day.js.org/docs/en/query/is-after)
