### ISSUE TITLE
Design the Home Page

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#57]
Make any required changes to the website home page to reflect current stylings and brand. 

Design work for the home page will be done in Figma and can be found there.

**Comment by o-ram** [comment]
Hi @segacy1! Just wanted to check in and see how the design work is going for the `Home page`. Anything you need? Anthony and I have draft copy in #58 and we're happy to modify it based on the final design. We're still hoping to complete the `Home page` by the end of Q2, which is crazily this month, so hoping we can package up the content + design for this and hand it off to dev soon. But let me know if that's feeling too tight on your end!

**Comment by segacy1** [comment]
Hi @o-ram! I have [2 options](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1104-4590) for the **homepage**:

1. Text only
2. Illustrated hero + text

With option 2 (and our **about** page designs), I did want to ask if the team would be interested in hiring an illustrator to create a few designs for the site (maybe 2-3 hero images, a few spot illustrations, team member photos, and a small icon set). If so, I'd happily work with the illustrator to provide direction. I think one case for illustrations is that they're a (generally) evergreen to add visual interest. We can mix and match and repurpose to create new images for the site without relying on photography and it keeps things looking cohesive/can also use them for other collateral beyond the website.

**Comment by AnthonyRollins** [comment]
@ segacy1 I would like to know what everyone thinks about illustrations, but I like illustrations over photos because they are more evergreen and not dependent on staff to be at the center of all images. My only concern and this might not be a thing based on the direction you can provide, is does that make our website too playful and abstract?

As for the Home page, I like the brand mark on top of the heading, so I am leaning towards no image, but if people like the other option, we have some [new images we got from our last retreat](https://drive.google.com/drive/u/0/folders/1GnZZBkr7MRL525ByMgdfWlnmXrnAlrCg), and there are some landscape photos of LA that I think would work.

**Comment by segacy1** [comment]
@AnthonyRollins yes, it definitely depends on the illustration style we go with! Ideally, we can share the brand guidelines/do’s and don’ts we came up with to help guide the illustrator too. I think even just expanding our pattern collection for moments like [this](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=677-2275&t=mz7uMaBldLk1aFFh-4) or creating a small icon set that includes human-centered icons or illustrations like [these](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1313-3999&t=mz7uMaBldLk1aFFh-4) would have an impact. I could put together a list of exactly what I have in mind/what illustrations id request if that would help!

@machikoyasuda also shared [this website](url) with me that's pretty cool. I think we can definitely develop something that feels like Compiler but gives us a little more flexibility in our designs. 

As for the mocks, I was thinking that for the [last one that doesn't have a brand mark in the nav](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1204-4318&t=mz7uMaBldLk1aFFh-4), we could potentially have a bespoke illustration that says our name. 

All that being said, if we just want to get something out this month and shift our focus to the about page (and any illustration that come with that), I like the one you selected and I think that certainly works!

**Comment by o-ram** [comment]
@segacy1 Anthony and I spoke yesterday, and I think we are all in agreement that we want to go with the text-only option so we can keep to the roadmap timeline. We definitely love the idea of illustrations, and are thinking that could be the plan for Home Page v2, when the time comes.

That said, I think where we stand is:
- Design is done (text only option)
- copy is done. Final copy is in #58 and I left a comment in Figma. LMK if you have any questions!

If that tracks with your thinking, then we can focus on handing this off to dev and move on to about!

**Comment by segacy1** [comment]
Sounds good! Just updated the copy and will update the figma style library today to match the direction we're going with so everything can be ready for dev as of tomorrow.

**Comment by segacy1** [comment]
Updated everything [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1355-3984)! Should be good to go.

**Comment by AnthonyRollins** [comment]
@segacy1 The heading copy is correct, but the `we build software for government` sub-heading should use this copy:

`Compiler is a woman-owned software consultancy that’s passionate about making government tech solutions easy-to-use 
 and accessible for all.` 

Let's update the copy. I will ask about the best way to send the final copy and design to the dev team, but I think having everything in Figma should be the best approach.

**Comment by o-ram** [comment]
@AnthonyRollins the `we build software for government` copy is what we had worked out in #58 and we identified as needing changing in Figma, so I asked Segacy to change it. Did you mean that you wanted the copy in Figma to be the final?

**Comment by segacy1** [comment]
All good! [Updated](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1355-3984).

**Comment by AnthonyRollins** [comment]
Perfect! I think we can close out this issue.
