### ISSUE TITLE
Copy for Home page

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#58]
As this copy will be simple (~ 2 sentences), Anthony and Olivia will take care of drafting and finalizing.

**Comment by AnthonyRollins** [comment]
@o-ram We might be able to use the top `h1` section from our [Compiler Lo-Fi Wireframes](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#) content. Let me know what you think you about combining it.

**Comment by o-ram** [comment]
@AnthonyRollins I like that! Simple and to the point. So the text would look something like:

### Software built by humans, for humans, in LA

Compiler is a woman-owned software consultancy that’s passionate about making government tech solutions easy-to-use and accessible for all. 

--
And using the current page as a reference, the header text would replace `we build software for the government`, and the other sentence would go below it. Is that what you're envisioning?
<img width="1181" alt="Screenshot 2023-05-15 at 11 49 15 AM" src="https://github.com/compilerla/compiler.la/assets/92001064/4fef835c-3e9a-4cf0-9cbe-18aeeb6c952b">

**Comment by AnthonyRollins** [comment]
@o-ram That was my thought. Let's see what the design looks like to see if we need more information.

**Comment by o-ram** [comment]
Final copy (headings here do not correspond to style of copy in official designs):

> ### Software built by humans, for humans, in LA
> we build software for the government

**Comment by AnthonyRollins** [comment]
Final copy sent to @segacy1 in #57
