### ISSUE TITLE
Design the About Page

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#59]
Design the new About page for the Compiler website.

All design work will be done in Figma and can be found there.

**Comment by o-ram** [comment]
Hello again @segacy1! Wanted to check in on how the design work is going for the `About page` as well and if you needed anything. Anthony and I have not formally started any of the content yet, but we have made some issues for tracking content work that needs to be done for all sections, especially anything involving images or testimonials.

**Comment by segacy1** [comment]
Hi @o-ram! I've updated the 2 directions we liked for this page [here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1059-2561). 

To the right, I also dropped in the watercolor team photo illustrations next to the original style proposed. As I noted on the homepage ticket, I think it would be great to have an illustrator create new, bespoke collateral for us to use across the site and beyond. If the team would be interested, I'd happily work with the illustrator to get what we need!

The immediate next step here would be for the team to decide which direction we'd like to move forward with, as that will determine the font styles we use across the site and will allow me to create a copy doc for you.

**Comment by AnthonyRollins** [comment]
@segacy1 We are ready for the content doc based on the designs for the second version (without the button) of [Option #2](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1059-2561&mode=design&t=AiSsvA3q1X25zYNZ-0). @o-ram mentioned that you would be able to provide it so we can start filling it with content.

**Comment by o-ram** [comment]
Yes, we both agreed on the second version! To address the point about bringing in an illustrator - similar to the home page, we definitely like the idea and want to do it at some point, but paused on that path for the about page as well to keep things moving. 

Also, with the copy doc Anthony mentioned, I was referring to your comment that picking a design would allow you to 

> determine the font styles we use across the site and will allow me to create a copy doc for you.

Just wanted to flag in case that was helpful! Thanks!

**Comment by segacy1** [comment]
Sounds good, will get that to you this week!

**Comment by AnthonyRollins** [comment]
@segacy1 Would you like to close out this issue or keep it open as there are still a few to-dos you mentioned in the Figma design?

**Comment by segacy1** [comment]
Let's keep it open if that's cool with you both! Planning to close this Friday.

**Comment by segacy1** [comment]
Updated the icon to a bus and marking this as complete!
