### ISSUE TITLE
Build out footer

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#6]
## Content
* [x] Check-in with Haley
* [x] @AnthonyRollins Respond to questions and add updates to [lo-fi wireframes](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#)
* [x] Haley making edits to [content](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#) strategy
* [ ] ~Finalize homepage [content](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#) strategy~ Not needed for this ticket
* [x] Send footer content to designer
## Design
* [ ] ~Vyki to check in with Kristi~
* [x] Send designer final content / strategy
* [x] Approve final design drafts for footer
## Implementation
- [ ] Develop footer based on design specs

## Resources 
- Prior art / initial [Figma design](https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website?node-id=0%3A1) (not final, but to give an idea)
- [Lo-Fi Wireframe ](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#)

**Comment by AnthonyRollins** [comment]
@angela-tran Add some additional tasks for content, design, and implementation. Let me know if we should build out the implementation tasks to include a few more steps. I will update these tasks with all the approved designs once we get to that point, so you don't have too look around

**Comment by AnthonyRollins** [comment]
@vykster Checking on the content strategy. Do we [Compiler] need to finalize the content, or were you planning to send that back over to Haley for a final run-through? If you cc me or send me Haley's contact info, I would be happy to reach out.

**Comment by vykster** [comment]
it's totally up to you know. I think what Haley sent was incomplete and we
can finish it ourselves and/or ask for additional support from Haley. I can
intro you directly.

**Comment by AnthonyRollins** [comment]
@vykster Thanks! Haley had a few questions that I answered on the doc and is currently taking another stab at the content, prioritizing some footer content. Would you be able to send me Kristi's email address, so I can prepare to send her the footer content? Did you get a chance to see if she is available for more work?

**Comment by AnthonyRollins** [comment]
@thekaveman @angela-tran The [content](https://docs.google.com/document/d/1iIWa7jx5wzGU2RjyufJ_X13Q9RE5eAVYNpQ4aDW8E1E/edit#) is in a good place for you both to review and give feedback. There is one place that you both should pay close attention to the `Our Work`section. Let me know if you have any questions!

**Comment by thekaveman** [comment]
We have a new footer style for implementation!

![image](https://user-images.githubusercontent.com/1783439/192036957-695adc24-be96-4244-a8db-2718cce9d3da.png)
