### ISSUE TITLE
Draft copy for the About page

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#60]
Draft content for all sections of the "about" page

- [x] Headline
- [x] Recent Work (#84)
- [x] Our Philosophy (#85)
- [x] Client testimonials (#78)
- [x] Who we are/meet the team (#79)

TBD on whether we handle all copy for this page in-house or if we ask Haley to help.

**Comment by o-ram** [comment]
Splitting each section of about page needing copy into its own issue. This will serve as the primary checklist.

**Comment by machikoyasuda** [comment]
@o-ram @AnthonyRollins Is the Copy (Recent Work, Philosophy, Client testimonials) for the About page ready for Development?

**Comment by machikoyasuda** [comment]
Marking this as complete with https://docs.google.com/spreadsheets/d/16ehalxbx9DoTqOPAHkVUC_dIYa4PlP4RohVrZSNz0Gg/edit#gid=0
