### ISSUE TITLE
Development work for Home page

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#65]
This is a placeholder for the development work that will take place this quarter. Issues will be built out once designs and content are done.

**Comment by AnthonyRollins** [comment]
Here's the final copy/design for the new [home page](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1355-3984).

**Comment by machikoyasuda** [comment]
## Components
- Header (h1)
- Paragraph (p)
- Button (primary-button)
- Nav height
