### ISSUE TITLE
Development work for About page

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#66]
This is a placeholder for the development work that will take place this quarter. Issues will be built out once designs and content are done.

**Comment by segacy1** [comment]
Dropping assets for this page here
[about page assets.zip](https://github.com/compilerla/compiler.la/files/12403243/about.page.assets.zip)

**Comment by AnthonyRollins** [comment]
@segacy1 These assets don't include Shelby. I added a comment to the About page designs regarding the same issue.

**Comment by segacy1** [comment]
Added Shelby in the designs and including her image here: 
![shelby](https://github.com/compilerla/compiler.la/assets/33331853/59f8e785-3f2a-4eef-974d-262b01282229)

**Comment by machikoyasuda** [comment]
@segacy1 Can you re-export the image for Shelby so it matches the image sizes of the rest of the illustrations? It's a bit short:

<img width="1319" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/0572fc80-2e04-48f1-9a94-41a5b81c3802">

**Comment by segacy1** [comment]
![shelby](https://github.com/compilerla/compiler.la/assets/33331853/aaaf2ffe-f5e1-4336-96eb-8879715bec5d)
@machikoyasuda try this one
