### ISSUE TITLE
Q3 2022 sprint

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#7]
**Due date:** September 30, 2022

## Background

The focus for Q3 will be to add content targeting the "potential client" audience type - i.e. those that may want to hire Compiler.

## Tasks

* [ ] #6

**Comment by AnthonyRollins** [comment]
@thekaveman @angela-tran Let me know if this is the correct use case, but could we use the Github `Milestone` feature to capture this issue, and add #6 to the milestone?

**Comment by thekaveman** [comment]
Closing per @AnthonyRollins suggestion, [Milestone created](https://github.com/compilerla/compiler.la/milestone/1)
