### ISSUE TITLE
Obtain client testimonials

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#78]
One of the sections for the `About page` calls for client testimonials. We ideally would like to have 2-3 that we can feature on the page.

This issue specifically tracks the tasks related to getting those testimonials, such as

- [x] Identify target clients
- [x] Draft email and testimonial copy ([doc for planning here](https://app.clickup.com/8631512/v/dc/87d6r-9800))
- [x] Coordinate with the appropriate individuals to contact the clients
- [x] Finalize the copy as well as who to attribute it to
- [x] Send requests to at least 2 clients
- [x] Insert copy into about page copy doc for testimonial 1
- [ ] Insert copy into about page copy doc for testimonial 2

**Comment by o-ram** [comment]
Hi @vykster! For the About page of the website, we are aiming to have 2-3 client testimonials. We are currently in the early stages of planning out copy for the page and have some things related to the testimonials section for you to give thoughts on:

1. We need one from Gillian and would like your thoughts on the approach for getting her signoff for this, specifically

- Should we draft something up for her, or would you like to?
- Once we have something to run by her, we were thinking the ask should come from you, but we aren't intending to add things to your plate, so let us know if you have a different preference.

2. We need 1-2 more from other clients

- @AnthonyRollins mentioned you had 2 other clients in mind. Which clients are they and how can we help obtain those? Happy to help however we can!

Again, we don't want to add things to your plate so as we go about figuring out the logistics for having these in hand and ready for the website, we're happy to do all we can.

**Comment by o-ram** [comment]
@vykster just checking in on the questions in the above comment!

**Comment by AnthonyRollins** [comment]
@o-ram I spoke with Vyki briefly about this at our Growth meeting, and she mentioned that we could contact Giilian for a quote. It will be best for us to draft something, so let's start putting together some ideas on what that could be (likely focus on something; Customer Success, benefits, etc.).

As for other clients, while still a part of Cal-ITP, we could ask a few others on the project that could offer a different perspective - a full list of other clients can be found in our [growth notes](https://app.clickup.com/8631512/v/dc/87d6r-3980). Could we schedule some time to discuss the other clients we want to use?

**Comment by o-ram** [comment]
Great, thank you! I can grab some time for us next week to discuss other clients and a draft for Gillian.

**Comment by o-ram** [comment]
@segacy1 for testimonials, is there a strict character limit? We are working on drafting some so busier clients can just read, give feedback, and sign off. I looked at the placeholder copy in the spreadsheet and noticed it's 71 characters. That's proving tricky so far to put something together for, so I was wondering if I can go higher than 71? Can make that work if needed, though. Thanks!

**Comment by AnthonyRollins** [comment]
@o-ram We are waiting for approval for one of the quotes, but we can close this issue as we wait. Dev will start next week, and we can exclude that quote until we hear if we can add it.
