### ISSUE TITLE
Team Image assets for About page "meet the team/who we are" section

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#79]
The About page on the website has a "Meet the Team" section, which calls for photos of team members and a group shot. The website made the decision to use the watercolors made during our 2022 holiday party for the team photos.

Team photos:
- [x] Talk with Shelby to get in touch with the artist so we can ask her to create watercolors for any team members who do not have one
- [x] Label [existing watercolors](https://drive.google.com/drive/folders/1ZjLKuKxRwmcYMFf0qn5glmGIDmUYO6_d) with name of person
- [x] Handoff images to design

Group photo:
- [ ] Finalize which image to use from existing options

**Comment by o-ram** [comment]
@AnthonyRollins While I was in website ticket creation mode, I went ahead and created the image assets ticket as well. Feel free to edit it however you'd like.

**Comment by AnthonyRollins** [comment]
@o-ram: Shebly reached out to Allison, the artist, to see if we can get more watercolor images.

**Comment by AnthonyRollins** [comment]
@o-ram, I've updated the about us content page to include all team members and their titles. I need to double check with everyone to ensure I am correctly representing everyone.

**Comment by segacy1** [comment]
Sounds good! Will use the order you have on the about page google sheet.

**Comment by AnthonyRollins** [comment]
Great - @o-ram closing out this issue as it is ready for dev.
