### ISSUE TITLE
Update Jobs page styling

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#82]
Segacy has updated the styling for the jobs page. You can find the styling in [Figma](https://figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=677-1890&t=yWGVmWiKAu2G6aBd-0). 

Let me know what other info you need.

**Comment by angela-tran** [comment]
I started work on this in #87, but forgot to assign myself to this issue - sorry about that!
