### ISSUE TITLE
About Page copy: Recent work section

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#84]
Draft copy for the Recent Work portion of the about page, keeping in mind that we have not started on the work page yet.

**Comment by o-ram** [comment]
Copy is drafted and can be found in the [copy spreadsheet](https://docs.google.com/spreadsheets/d/16ehalxbx9DoTqOPAHkVUC_dIYa4PlP4RohVrZSNz0Gg/edit#gid=0). We are having Scott weigh in before considering this done.

**Comment by AnthonyRollins** [comment]
Scott weighed in, and all content for recent work has been finalized.
