### ISSUE TITLE
Google Analytics script not loading

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#86]
1. Go to https://compiler.la
2. View developer console
3. See error:

```console
GET https://www.googletagmanager.com/gtag/js?id=G-2JY7J1TEN2 net::ERR_ADDRESS_INVALID
```

**Comment by angela-tran** [comment]
I tried to reproduce this, but the script loads for me 🤔 

![image](https://github.com/compilerla/compiler.la/assets/25497886/4bdfa65f-628a-4afe-a268-cdc566f265cd)

**Comment by thekaveman** [comment]
Doh, this was due to some overly aggressive Ad filtering on my home network 😁
