### ISSUE TITLE
Add capabilities statement

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/compiler.la#9]
## Content
- [x] Finalize content/design for capabilities statement

## Design
- [x] #16
- [x] Add two new buttons; `Get in touch` and `Capabilities Statement`
- [x] `Capabilities Statement` button should use styling form [Figma design](https://www.figma.com/file/fkRyBpWGDyaBh1kzaXIljo/Compiler-website?node-id=20%3A391) and should be first and `left-aligned` link to `compiler.la/capabilitites`. On-hover change background to `opacity: 70%;`
- [x] `Get in touch` button should appear next to the Capabilities button with Compiler green `#88B440` outline and `#ffffff` font mailto link: `hello@compiler.la`. On-hover change background to `opacity: 70%;`
- [x] `We build software for the government.` change to an `h1` and moved just under the logo 

## Implementation
- [x] Add a download button for the capabilities statement to the preview site, based on future Figma designs
- [x] Redirect `https://compiler.la/capabilities` to the capabilities statement downloadable file

**Comment by vykster** [comment]
wooo, yes please.

**Comment by angela-tran** [comment]
@AnthonyRollins I played around with the HTML/CSS a bit and have this so far:

![compilerla_links](https://user-images.githubusercontent.com/25497886/178080103-d2a7416a-c9ea-4c19-8ec1-bcda15b9bb2c.gif)

**Comment by AnthonyRollins** [comment]
@angela-tran I just checked the font contrast for our buttons, which failed with the white font.

- [ ] Let's change the button font color to `#000000` when it is on the background of the Compiler green `#88B440`.

**Comment by angela-tran** [comment]
> I would make the `we build software for the government` an `h1.` to make it more of a statement. Unless it is already an h1 and I can't tell the difference :)

It is indeed an h1 element 😄 Maybe your point though is that the styling should be different?

**Comment by AnthonyRollins** [comment]
@angela-tran, I guess I think it should be bigger, maybe?
